name: build
on:
 push:
  branches: [ main ]
 schedule:
  - cron: '*/10 * * * *'
  
 workflow_dispatch:
 
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
         ref: main
         fetch-depth: 0
        
      - name: print latest_commit
        shell: bash
        run: |
         git pull
         pastdate=$(date --date="${dataset_date} -3 day" +%Y-%m-%d);todaysdate=$(date +'%Y-%m-%d');commitcount=$(git log --pretty="%h %an %ad" --since=$pastdate --until=$todaysdate | wc -l)
         echo commit count = $commitcount between $pastdate and $todaysdate

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'push' }}
        run: git rev-list --after="24 hours" ${{ github.sha }} && echo "::set-output name=should_run::true"
  job2:
      needs: check_date
      if: ${{ needs.check_date.outputs.should_run != 'false' }}
      runs-on: ubuntu-latest
      name: do-something
      steps:
        - name: Print        
          run: echo '______________------_-----______________'
       
   
