name: .NET in Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: vjammula84/dockerhub:demoimage
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build and test
      run: dotnet build --no-restore
      uses: ./
      with:
        entrypoint: dotnet
        args: myApp/bin/Debug/net6.0/myApp.dll


    # dotnet "myApp/bin/Debug/net6.0/myApp.dll"
    # dotnet run --project "myApp/myApp.csproj"
    # - name: Test
    #   run: |
    #     dotnet test --no-build --verbosity normal
    # - name: Entry Test
    #   run: |
    #     COPY myApp/bin/Debug .
    #     ls
    #     ENTRYPOINT ["dotnet","net6.0/myApp.dll"] 
