name: .NET in Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: vjammula84/dockerhub:demoimage
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build --no-restore
        dotnet "myApp/bin/Debug/net6.0/myApp.dll"
    - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ""
          destination_branch: "main"
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: ":crown: *An automated PR*"              # Full markdown support, requires pr_title to be set
          #  pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body
          pr_reviewer: "vamsea2002"                         # Comma-separated list (no spaces)
          pr_assignee: "vamsea2002"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_draft: false                                    # Creates pull request as draft
          pr_allow_empty: true                              # Creates pull request even if there are no changes
          github_token: ${{ secrets.GITHUB_TOKEN }}        
    # dotnet run --project "myApp/myApp.csproj"
    # - name: Test
    #   run: |
    #     dotnet test --no-build --verbosity normal
    # - name: Entry Test
    #   run: |
    #     COPY myApp/bin/Debug .
    #     ls
    #     ENTRYPOINT ["dotnet","net6.0/myApp.dll"] 
