name: .NET in Container

on:
  push:
    branches: [ test_branch_2 ]
  pull_request:
    branches: [ test_branch_2 ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    container: vjammula84/dockerhub:demoimage
    steps:
    - uses: actions/checkout@v2    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        custom_tag: rest_tag
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    
