name: .NET in Container

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    container: vjammula84/dockerhub:demoimage
    steps:
    - uses: actions/checkout@v2    
        
    - name: Bump version and push tag
      id: tag_version
      uses: miguelfito/github-bump-and-tag-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        custom_tag: v1
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    
