name: .NET in Container

on:
  push:
    branches: [ test_branch_2 ]
  pull_request:
    branches: [ test_branch_2 ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    container: vjammula84/dockerhub:demoimage
    steps:
    - uses: actions/checkout@v2    

    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    
